INSERT INTO [dbo].[Colores] ([Id_Color], [Tipo_Color], [Precio_Color]) VALUES (1, N'Apilne', N'340')
INSERT INTO [dbo].[Colores] ([Id_Color], [Tipo_Color], [Precio_Color]) VALUES (2, N'Gris', N'200')
INSERT INTO [dbo].[Colores] ([Id_Color], [Tipo_Color], [Precio_Color]) VALUES (3, N'Rojo', N'500')
INSERT INTO [dbo].[Colores] ([Id_Color], [Tipo_Color], [Precio_Color]) VALUES (4, N'Negro', N'300')
INSERT INTO [dbo].[Colores] ([Id_Color], [Tipo_Color], [Precio_Color]) VALUES (5, N'Blanco', N'100')
