INSERT INTO [dbo].[Cuadros] ([Id_Cuadro], [Tipo_Cuadro], [Precio_Cuadro], [Modelo_Bicicleta]) VALUES (1, N'100A Acero', N'500', N'CAADOptimo')
INSERT INTO [dbo].[Cuadros] ([Id_Cuadro], [Tipo_Cuadro], [Precio_Cuadro], [Modelo_Bicicleta]) VALUES (2, N'100A Aluminio', N'650', N'CAADOptimo')
INSERT INTO [dbo].[Cuadros] ([Id_Cuadro], [Tipo_Cuadro], [Precio_Cuadro], [Modelo_Bicicleta]) VALUES (3, N'100C Carbono', N'1000', N'CAADOptimo')
INSERT INTO [dbo].[Cuadros] ([Id_Cuadro], [Tipo_Cuadro], [Precio_Cuadro], [Modelo_Bicicleta]) VALUES (4, N'200C Carbono Plus', N'1300', N'CAADOptimo')
INSERT INTO [dbo].[Cuadros] ([Id_Cuadro], [Tipo_Cuadro], [Precio_Cuadro], [Modelo_Bicicleta]) VALUES (5, N'100T Titanio', N'1550', N'CAADOptimo')
INSERT INTO [dbo].[Cuadros] ([Id_Cuadro], [Tipo_Cuadro], [Precio_Cuadro], [Modelo_Bicicleta]) VALUES (6, N'200T Titanio Plus', N'1800', N'CAADOptimo')
INSERT INTO [dbo].[Cuadros] ([Id_Cuadro], [Tipo_Cuadro], [Precio_Cuadro], [Modelo_Bicicleta]) VALUES (7, N'Synapse Carbon 1 RLE', N'1600', N'Synapse')
INSERT INTO [dbo].[Cuadros] ([Id_Cuadro], [Tipo_Cuadro], [Precio_Cuadro], [Modelo_Bicicleta]) VALUES (8, N'Synapse Carbon LTD RLE', N'1800', N'Synapse')
INSERT INTO [dbo].[Cuadros] ([Id_Cuadro], [Tipo_Cuadro], [Precio_Cuadro], [Modelo_Bicicleta]) VALUES (9, N'Synapse Carbon 2 RLE', N'2000', N'Synapse')
INSERT INTO [dbo].[Cuadros] ([Id_Cuadro], [Tipo_Cuadro], [Precio_Cuadro], [Modelo_Bicicleta]) VALUES (10, N'Synapse Carbon 2 RL', N'2100', N'Synapse')
INSERT INTO [dbo].[Cuadros] ([Id_Cuadro], [Tipo_Cuadro], [Precio_Cuadro], [Modelo_Bicicleta]) VALUES (10, N'Synapse Carbon 3 L', N'2500', N'Synapse')
